export const extraSmall = 'min-width: 360px'
export const small = 'min-width: 480px'
export const mediumSmall = 'min-width: 600px'
export const medium = 'min-width: 768px'
export const mediumLarge = 'min-width: 1080px'
export const large = 'min-width: 1280px'
export const extraLarge = 'min-width: 1440px'
